const FIXED_NAMES = {
  Arica: 'Arica',
  Camarones: 'Camarones',
  'General Lagos': 'General Lagos',
  Putre: 'Putre',
  'Alto Hospicio': 'Alto Hospicio',
  Camina: 'Camiña',
  Colchane: 'Colchane',
  Huara: 'Huara',
  Iquique: 'Iquique',
  Pica: 'Pica',
  'Pozo Almonte': 'Pozo Almonte',
  Antofagasta: 'Antofagasta',
  Calama: 'Calama',
  'Maria Elena': 'María Elena',
  Mejillones: 'Mejillones',
  Ollague: 'Ollagüe',
  'San Pedro de Atacama': 'San Pedro de Atacama',
  'Sierra Gorda': 'Sierra Gorda',
  Taltal: 'Taltal',
  Tocopilla: 'Tocopilla',
  'Alto del Carmen': 'Alto del Carmen',
  Caldera: 'Caldera',
  Chanaral: 'Chañaral',
  Copiapo: 'Copiapó',
  'Diego de Almagro': 'Diego de Almagro',
  Freirina: 'Freirina',
  Huasco: 'Huasco',
  'Tierra Amarilla': 'Tierra Amarilla',
  Vallenar: 'Vallenar',
  Andacollo: 'Andacollo',
  Canela: 'Canela',
  Combarbala: 'Combarbalá',
  Coquimbo: 'Coquimbo',
  Illapel: 'Illapel',
  'La Higuera': 'La Higuera',
  'La Serena': 'La Serena',
  'Los Vilos': 'Los Vilos',
  'Monte Patria': 'Monte Patria',
  Ovalle: 'Ovalle',
  Paiguano: 'Paiguano',
  Punitaqui: 'Punitaqui',
  'Rio Hurtado': 'Río Hurtado',
  Salamanca: 'Salamanca',
  Vicuna: 'Vicuña',
  Algarrobo: 'Algarrobo',
  Cabildo: 'Cabildo',
  Calera: 'Calera',
  'Calle Larga': 'Calle Larga',
  Cartagena: 'Cartagena',
  Casablanca: 'Casablanca',
  Catemu: 'Catemu',
  Concon: 'Concón',
  'El Quisco': 'El Quisco',
  'El Tabo': 'El Tabo',
  Hijuelas: 'Hijuelas',
  'Isla de Pascua': 'Isla de Pascua',
  'Juan Fernandez': 'Juan Fernández',
  'La Cruz': 'La Cruz',
  'La Ligua': 'La Ligua',
  Limache: 'Limache',
  Llaillay: 'Llaillay',
  'Los Andes': 'Los Andes',
  Nogales: 'Nogales',
  Olmue: 'Olmué',
  Panquehue: 'Panquehue',
  Papudo: 'Papudo',
  Petorca: 'Petorca',
  Puchuncavi: 'Puchuncaví',
  Putaendo: 'Putaendo',
  Quillota: 'Quillota',
  Quilpue: 'Quilpué',
  Quintero: 'Quintero',
  Rinconada: 'Rinconada',
  'San Antonio': 'San Antonio',
  'San Esteban': 'San Esteban',
  'San Felipe': 'San Felipe',
  'Santa Maria': 'Santa María',
  'Santo Domingo': 'Santo Domingo',
  Valparaiso: 'Valparaíso',
  'Villa Alemana': 'Villa Alemana',
  'Vina del Mar': 'Viña del Mar',
  Zapallar: 'Zapallar',
  Alhue: 'Alhué',
  Buin: 'Buin',
  'Calera de Tango': 'Calera de Tango',
  Cerrillos: 'Cerrillos',
  'Cerro Navia': 'Cerro Navia',
  Colina: 'Colina',
  Conchali: 'Conchalí',
  Curacavi: 'Curacaví',
  'El Bosque': 'El Bosque',
  'El Monte': 'El Monte',
  'Estacion Central': 'Estación Central',
  Huechuraba: 'Huechuraba',
  Independencia: 'Independencia',
  'Isla de Maipo': 'Isla de Maipo',
  'La Cisterna': 'La Cisterna',
  'La Florida': 'La Florida',
  'La Granja': 'La Granja',
  'La Pintana': 'La Pintana',
  'La Reina': 'La Reina',
  Lampa: 'Lampa',
  'Las Condes': 'Las Condes',
  'Lo Barnechea': 'Lo Barnechea',
  'Lo Espejo': 'Lo Espejo',
  'Lo Prado': 'Lo Prado',
  Macul: 'Macul',
  Maipu: 'Maipú',
  'Maria Pinto': 'María Pinto',
  Melipilla: 'Melipilla',
  Nunoa: 'Ñuñoa',
  'Padre Hurtado': 'Padre Hurtado',
  Paine: 'Paine',
  'Pedro Aguirre Cerda': 'Pedro Aguirre Cerda',
  Penaflor: 'Peñaflor',
  Penalolen: 'Peñalolén',
  Pirque: 'Pirque',
  Providencia: 'Providencia',
  Pudahuel: 'Pudahuel',
  'Puente Alto': 'Puente Alto',
  Quilicura: 'Quilicura',
  'Quinta Normal': 'Quinta Normal',
  Recoleta: 'Recoleta',
  Renca: 'Renca',
  'San Bernardo': 'San Bernardo',
  'San Joaquin': 'San Joaquín',
  'San Jose de Maipo': 'San José de Maipo',
  'San Miguel': 'San Miguel',
  'San Pedro': 'San Pedro',
  'San Ramon': 'San Ramón',
  Santiago: 'Santiago',
  Talagante: 'Talagante',
  Tiltil: 'Tiltil',
  Vitacura: 'Vitacura',
  Chepica: 'Chépica',
  Chimbarongo: 'Chimbarongo',
  Codegua: 'Codegua',
  Coinco: 'Coinco',
  Coltauco: 'Coltauco',
  Donihue: 'Doñihue',
  Graneros: 'Graneros',
  'La Estrella': 'La Estrella',
  'Las Cabras': 'Las Cabras',
  Litueche: 'Litueche',
  Lolol: 'Lolol',
  Machali: 'Machalí',
  Malloa: 'Malloa',
  Marchihue: 'Marchihue',
  Mostazal: 'Mostazal',
  Nancagua: 'Nancagua',
  Navidad: 'Navidad',
  Olivar: 'Olivar',
  Palmilla: 'Palmilla',
  Paredones: 'Paredones',
  Peralillo: 'Peralillo',
  Peumo: 'Peumo',
  Pichidegua: 'Pichidegua',
  Pichilemu: 'Pichilemu',
  Placilla: 'Placilla',
  Pumanque: 'Pumanque',
  'Quinta de Tilcoco': 'Quinta de Tilcoco',
  Rancagua: 'Rancagua',
  Rengo: 'Rengo',
  Requinoa: 'Requínoa',
  'San Fernando': 'San Fernando',
  'San Vicente': 'San Vicente',
  'Santa Cruz': 'Santa Cruz',
  Cauquenes: 'Cauquenes',
  Chanco: 'Chanco',
  Colbun: 'Colbún',
  Constitucion: 'Constitución',
  Curepto: 'Curepto',
  Curico: 'Curicó',
  Empedrado: 'Empedrado',
  Hualane: 'Hualañé',
  Licanten: 'Licantén',
  Linares: 'Linares',
  Longavi: 'Longaví',
  Maule: 'Maule',
  Molina: 'Molina',
  Parral: 'Parral',
  Pelarco: 'Pelarco',
  Pelluhue: 'Pelluhue',
  Pencahue: 'Pencahue',
  Rauco: 'Rauco',
  Retiro: 'Retiro',
  'Rio Claro': 'Río Claro',
  Romeral: 'Romeral',
  'Sagrada Familia': 'Sagrada Familia',
  'San Clemente': 'San Clemente',
  'San Javier': 'San Javier',
  'San Rafael': 'San Rafael',
  Talca: 'Talca',
  Teno: 'Teno',
  Vichuquen: 'Vichuquén',
  'Villa Alegre': 'Villa Alegre',
  'Yerbas Buenas': 'Yerbas Buenas',
  Bulnes: 'Bulnes',
  Chillan: 'Chillán',
  'Chillan Viejo': 'Chillán Viejo',
  Cobquecura: 'Cobquecura',
  Coelemu: 'Coelemu',
  Coihueco: 'Coihueco',
  'El Carmen': 'El Carmen',
  Ninhue: 'Ninhue',
  Niquen: 'Ñiquén',
  Pemuco: 'Pemuco',
  Pinto: 'Pinto',
  Portezuelo: 'Portezuelo',
  Quillon: 'Quillón',
  Quirihue: 'Quirihue',
  Ranquil: 'Ránquil',
  'San Carlos': 'San Carlos',
  'San Fabian': 'San Fabián',
  'San Ignacio': 'San Ignacio',
  'San Nicolas': 'San Nicolás',
  Treguaco: 'Treguaco',
  Yungay: 'Yungay',
  'Alto Biobio': 'Alto Biobío',
  Antuco: 'Antuco',
  Arauco: 'Arauco',
  Cabrero: 'Cabrero',
  Canete: 'Cañete',
  Chiguayante: 'Chiguayante',
  Concepcion: 'Concepción',
  Contulmo: 'Contulmo',
  Coronel: 'Coronel',
  Curanilahue: 'Curanilahue',
  Florida: 'Florida',
  Hualpen: 'Hualpén',
  Hualqui: 'Hualqui',
  Laja: 'Laja',
  Lebu: 'Lebu',
  'Los Alamos': 'Los Álamos',
  'Los Angeles': 'Los Ángeles',
  Lota: 'Lota',
  Mulchen: 'Mulchén',
  Nacimiento: 'Nacimiento',
  Negrete: 'Negrete',
  Penco: 'Penco',
  Quilaco: 'Quilaco',
  Quilleco: 'Quilleco',
  'San Pedro de la Paz': 'San Pedro de la Paz',
  'San Rosendo': 'San Rosendo',
  'Santa Barbara': 'Santa Bárbara',
  'Santa Juana': 'Santa Juana',
  Talcahuano: 'Talcahuano',
  Tirua: 'Tirúa',
  Tome: 'Tomé',
  Tucapel: 'Tucapel',
  Yumbel: 'Yumbel',
  Angol: 'Angol',
  Carahue: 'Carahue',
  Cholchol: 'Cholchol',
  Collipulli: 'Collipulli',
  Cunco: 'Cunco',
  Curacautin: 'Curacautín',
  Curarrehue: 'Curarrehue',
  Ercilla: 'Ercilla',
  Freire: 'Freire',
  Galvarino: 'Galvarino',
  Gorbea: 'Gorbea',
  Lautaro: 'Lautaro',
  Loncoche: 'Loncoche',
  Lonquimay: 'Lonquimay',
  'Los Sauces': 'Los Sauces',
  Lumaco: 'Lumaco',
  Melipeuco: 'Melipeuco',
  'Nueva Imperial': 'Nueva Imperial',
  'Padre Las Casas': 'Padre Las Casas',
  Perquenco: 'Perquenco',
  Pitrufquen: 'Pitrufquén',
  Pucon: 'Pucón',
  Puren: 'Purén',
  Renaico: 'Renaico',
  Saavedra: 'Saavedra',
  Temuco: 'Temuco',
  'Teodoro Schmidt': 'Teodoro Schmidt',
  Tolten: 'Toltén',
  Traiguen: 'Traiguén',
  Victoria: 'Victoria',
  Vilcun: 'Vilcún',
  Villarrica: 'Villarrica',
  Corral: 'Corral',
  Futrono: 'Futrono',
  'La Union': 'La Unión',
  'Lago Ranco': 'Lago Ranco',
  Lanco: 'Lanco',
  'Los Lagos': 'Los Lagos',
  Mafil: 'Máfil',
  Mariquina: 'Mariquina',
  Paillaco: 'Paillaco',
  Panguipulli: 'Panguipulli',
  'Rio Bueno': 'Río Bueno',
  Valdivia: 'Valdivia',
  Ancud: 'Ancud',
  Calbuco: 'Calbuco',
  Castro: 'Castro',
  Chaiten: 'Chaitén',
  Chonchi: 'Chonchi',
  Cochamo: 'Cochamó',
  'Curaco de Velez': 'Curaco de Vélez',
  Dalcahue: 'Dalcahue',
  Fresia: 'Fresia',
  Frutillar: 'Frutillar',
  Futaleufu: 'Futaleufú',
  Hualaihue: 'Hualaihué',
  Llanquihue: 'Llanquihue',
  'Los Muermos': 'Los Muermos',
  Maullin: 'Maullín',
  Osorno: 'Osorno',
  Palena: 'Palena',
  'Puerto Montt': 'Puerto Montt',
  'Puerto Octay': 'Puerto Octay',
  'Puerto Varas': 'Puerto Varas',
  Puqueldon: 'Puqueldón',
  Purranque: 'Purranque',
  Puyehue: 'Puyehue',
  Queilen: 'Queilén',
  Quellon: 'Quellón',
  Quemchi: 'Quemchi',
  Quinchao: 'Quinchao',
  'Rio Negro': 'Río Negro',
  'San Juan de la Costa': 'San Juan de la Costa',
  'San Pablo': 'San Pablo',
  Aysen: 'Aisén',
  'Chile Chico': 'Chile Chico',
  Cisnes: 'Cisnes',
  Cochrane: 'Cochrane',
  Coyhaique: 'Coyhaique',
  Guaitecas: 'Guaitecas',
  'Lago Verde': 'Lago Verde',
  OHiggins: "O'Higgins",
  'Rio Ibanez': 'Río Ibáñez',
  Tortel: 'Tortel',
  Antartica: 'Antártica',
  'Cabo de Hornos': 'Cabo de Hornos',
  'Laguna Blanca': 'Laguna Blanca',
  Natales: 'Natales',
  Porvenir: 'Porvenir',
  Primavera: 'Primavera',
  'Punta Arenas': 'Punta Arenas',
  'Rio Verde': 'Río Verde',
  'San Gregorio': 'San Gregorio',
  Timaukel: 'Timaukel',
  'Torres del Paine': 'Torres del Paine',
};

function fixComunaName(comuna) {
  try {
    return FIXED_NAMES[comuna];
  } catch {
    return comuna;
  }
}

export default fixComunaName;
